kind: Service
apiVersion: v1
metadata:
  name: railway-timetable-service-canary
spec:
  type: NodePort
  selector:
    app: railway-timetable
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30090

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: railway-timetable-deployment-canary
  labels:
    app: railway-timetable
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: railway-timetable
      track: canary
  template:
    metadata:
      labels:
        app: railway-timetable
        track: canary
    spec:
      containers:
      - name: railway-timetable
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
